USB_VID = 0x04D8
USB_PID = 0xED36
USB_PRODUCT = "Eltech Nonthue M0"
USB_MANUFACTURER = "Microchip"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ, GD25Q16C"
LONGINT_IMPL = MPZ
